// Code generated by generator, DO NOT EDIT.
package example

import (
	"context"
	bson "go.mongodb.org/mongo-driver/bson"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	mongo "go.mongodb.org/mongo-driver/mongo"
	"time"
)

type userRepository struct {
	db *mongo.Database
}

func NewUserRepository(db *mongo.Database) UserRepository {
	return &userRepository{db: db}
}
func (x *userRepository) getCollection() *mongo.Collection {
	return x.db.Collection("user")
}
func (x *userRepository) Insert(ctx context.Context, input *User) error {
	if input.ID.IsZero() {
		input.ID = primitive.NewObjectID()
	}
	if input.CreatedAt.IsZero() {
		input.CreatedAt = time.Now()
	}
	if res, err := x.getCollection().InsertOne(ctx, input); err != nil {
		return err
	} else if res.InsertedID != nil {
		return nil
	}
	return nil
}
func (x *userRepository) GetPrimitive(ctx context.Context, id primitive.ObjectID) (*User, error) {
	res := User{}
	err := x.getCollection().FindOne(ctx, bson.D{{"_id", id}}).Decode(&res)
	if err != nil {
		if err == mongo.ErrNoDocuments {
			return nil, nil
		}
		return nil, err
	}
	return &res, nil
}
func (x *userRepository) Get(ctx context.Context, id string) (*User, error) {
	_id, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, err
	}
	return x.GetPrimitive(ctx, _id)
}
func (x *userRepository) Delete(ctx context.Context, id primitive.ObjectID) (*mongo.DeleteResult, error) {
	res, err := x.getCollection().DeleteOne(ctx, bson.D{{"_id", id}})
	if err != nil {
		if err == mongo.ErrNoDocuments {
			return nil, nil
		}
		return nil, err
	}
	return res, nil
}
func (x *userRepository) List(ctx context.Context) ([]User, error) {
	cur, err := x.getCollection().Find(ctx, bson.D{})
	if err != nil {
		return nil, err
	}
	res := []User{}
	if err := cur.All(ctx, &res); err != nil {
		return nil, err
	}
	return res, nil
}
func (x *userRepository) GetByShoeSizeAndName(ctx context.Context, shoeSize int, name string) (*User, error) {
	res := User{}
	err := x.getCollection().FindOne(ctx, bson.D{{"shoe_size", shoeSize}, {"name", name}}).Decode(&res)
	if err != nil {
		if err == mongo.ErrNoDocuments {
			return nil, nil
		}
		return nil, err
	}
	return &res, nil
}
func (x *userRepository) ListByName(ctx context.Context, name string) ([]User, error) {
	cur, err := x.getCollection().Find(ctx, bson.D{{"name", name}})
	if err != nil {
		return nil, err
	}
	res := []User{}
	if err := cur.All(ctx, &res); err != nil {
		return nil, err
	}
	return res, nil
}
func (x *userRepository) ListByNameAndAge(ctx context.Context, name string, age int) ([]User, error) {
	cur, err := x.getCollection().Find(ctx, bson.D{{"name", name}, {"age", age}})
	if err != nil {
		return nil, err
	}
	res := []User{}
	if err := cur.All(ctx, &res); err != nil {
		return nil, err
	}
	return res, nil
}
func (x *userRepository) ListByProfile(ctx context.Context, profile Profile) ([]User, error) {
	cur, err := x.getCollection().Find(ctx, bson.D{{"profile", profile}})
	if err != nil {
		return nil, err
	}
	res := []User{}
	if err := cur.All(ctx, &res); err != nil {
		return nil, err
	}
	return res, nil
}

type UserRepository interface {
	Delete(ctx context.Context, id primitive.ObjectID) (*mongo.DeleteResult, error)
	Get(ctx context.Context, id string) (*User, error)
	GetByShoeSizeAndName(ctx context.Context, shoeSize int, name string) (*User, error)
	GetPrimitive(ctx context.Context, id primitive.ObjectID) (*User, error)
	Insert(ctx context.Context, input *User) error
	List(ctx context.Context) ([]User, error)
	ListByName(ctx context.Context, name string) ([]User, error)
	ListByNameAndAge(ctx context.Context, name string, age int) ([]User, error)
	ListByProfile(ctx context.Context, profile Profile) ([]User, error)
	getCollection() *mongo.Collection
}
type Repository struct {
	User UserRepository
}

func NewRepository(db *mongo.Database) *Repository {
	return &Repository{User: NewUserRepository(db)}
}
